apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod
namePrefix: prod-


resources:
- ../../apps/webapp

configMapGenerator:
- behavior: merge
  literals:
  - ENVIRONMENT=production
  - VERSION=1.0.0
  - LOG_LEVEL=warning
  - FEATURE_FLAG_NEW_UI=false
  name: webapp-config

replicas:
- count: 3
  name: webapp

images:
- name: nginxdemos/hello
  newTag: latest
labels:
- includeSelectors: true
  pairs:
    environment: prod
    team: platform
