apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev
namePrefix: dev-


resources:
- ../../apps/webapp

configMapGenerator:
- behavior: merge
  literals:
  - ENVIRONMENT=development
  - VERSION=dev-latest
  - LOG_LEVEL=debug
  - FEATURE_FLAG_NEW_UI=true
  name: webapp-config

replicas:
- count: 1
  name: webapp

images:
- name: nginxdemos/hello
  newTag: latest
labels:
- includeSelectors: true
  pairs:
    environment: dev
    team: platform

